
### Coderhouse - Data Science
Profe Jorge Ruiz

Para usar una libreria y sus métodos es necesario instalarla primero. Una vez ha sido instalada es necesario importarla en el notebook en el que se va a usar.<br>

Para importar usamos el comando <code> import </code> seguido del nombre de la libreria, en la mayoria de casos se utiliza la clausula <code> as </code> para asignar un "apodo", usualmente más corto que facilite su uso.

In [51]:
# importar la libreria
import numpy as np

In [52]:
lista_prueba=list(range(10))
lista_prueba

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Crear narray

In [53]:
Npa = np.array([10,2])
Npa

array([10,  2])

In [54]:
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# agregar nuevo valor a un array
new_value = 5

my_array = np.append(Npa, new_value)

print(my_array)

[0 1 2 3 4 5 6 7 8 9 5]


In [56]:
# eliminar un valor por posición

index_to_delete = 10

my_array = np.delete(my_array, index_to_delete)

print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
Np_cero = np.zeros(10) #float o decimales
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
Np_cero_int = np.zeros(5, dtype=int) #int o entero
Np_cero_int

array([0, 0, 0, 0, 0])

In [59]:
Np_uno = np.ones(10, dtype=int)
Np_uno

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [60]:
Np_relleno = np.full(5, 11) # (tamaño, valor)
Np_relleno

array([11, 11, 11, 11, 11])

In [61]:
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
Np_rango = np.arange(10.0) # funciona igual que range
Np_rango

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

La principal diferencia entre range y arange es que range genera una secuencia de números enteros, mientras que arange puede generar una secuencia de números en punto flotante. Además, arange es parte del módulo NumPy

In [63]:
Np_rango = np.arange(1, 10) # funciona igual que range
Np_rango

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
Np_rango = np.arange(2.0, 10.0, 2) # funciona igual que range
Np_rango

array([2., 4., 6., 8.])

In [65]:
"""
np.random.randint(10, size=(3, 4)) es una llamada a la función randint del módulo numpy.random de la librería NumPy.
Esta función genera un array de números enteros aleatorios con valores que van desde 0 hasta el número especificado como primer argumento (en este caso, 10).

El segundo argumento de la función, size=(3, 4), especifica las dimensiones del array resultante.
En este caso, se genera un array de 3 filas y 4 columnas, lo que significa que el array resultante tendrá una forma de (3, 4).
"""

Np_random_dimensiones = np.random.randint(10, size=(3, 4)) #valores aleatorios
#Np_random_dimensiones = np.random.randint(5, 10, size=(3, 4)) #valores aleatorios entre 5 Y 9
Np_random_dimensiones

array([[4, 1, 0, 7],
       [4, 8, 1, 1],
       [5, 1, 1, 4]])

### Propiedades de los arrays

#### Dimesión

In [66]:
Np_random_dimensiones.ndim

#ndim devuelve el número de dimensiones del array

2

#### Forma

In [67]:
Np_random_dimensiones.shape

#shape: devuelve la forma (número de filas y columnas) del array.

(3, 4)

#### Tamaño

In [68]:
Np_random_dimensiones.size

#size: devuelve el número total de elementos en el array.

12

In [69]:
Np_random_dimensiones.max()

# max y min: devuelven el valor máximo y mínimo en el array, respectivamente.

8

otro ejemplo

In [70]:
Np_random_dimensiones.flatten()

# flatten: devuelve una copia unidimensional del array original.

array([4, 1, 0, 7, 4, 8, 1, 1, 5, 1, 1, 4])

In [71]:
print('narray ', Npa)
print('dimensiones ', Npa.ndim)
print('forma ', Npa.shape)
print('tamaño ', Npa.size)

narray  [0 1 2 3 4 5 6 7 8 9]
dimensiones  1
forma  (10,)
tamaño  10


#### Tipo de dato

In [72]:
print(Np_cero)
print(Np_cero.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64


In [73]:
print(Np_cero_int)
print(Np_cero_int.dtype)

[0 0 0 0 0]
int64


In [74]:
Np_random_dimensiones.dtype

dtype('int64')

In [75]:
Np_random_dimensiones

array([[4, 1, 0, 7],
       [4, 8, 1, 1],
       [5, 1, 1, 4]])

#### Tamaño del elemento

In [76]:
print(Np_random_dimensiones.itemsize, 'bytes')

8 bytes


#### Tamaño total

In [77]:
print(Np_random_dimensiones.nbytes, 'bytes')

96 bytes


----------------------------
### tip:
Usualmente cuando se crea o carga un conjunto de datos se asigna un tipo de dato de forma ***automática***. Esto sucede porque al crear el objeto se reserva un espacio en ***memoria*** para cada dato. No obstante, cada tipo de dato representa un ***consumo*** de memoria diferente.<br>
Veamos algunos ejemplos:

In [78]:
x = np.array([1.,2,3])
x.dtype

dtype('float64')

In [79]:
"""
El tamaño de x es de 24 bytes.
Esto se debe a que x es un array de NumPy con 3 elementos de tipo float64, que en NumPy se representan
utilizando 64 bits o 8 bytes por elemento. Por lo tanto, el tamaño total de x es de 3 elementos multiplicado por 8 bytes por elemento,
lo que resulta en un total de 24 bytes.
"""
x = np.array([1,2,3], dtype=np.float64)
print('Usando float64:')
print('tamaño elemento', x.itemsize, 'tamaño total', x.nbytes)


Usando float64:
tamaño elemento 8 tamaño total 24


In [80]:
x = np.array([1,2,3], dtype=np.int8)
print('Usando int:')
print('tamaño elemento', x.itemsize, 'tamaño total', x.nbytes)

Usando int:
tamaño elemento 1 tamaño total 3


Alto ahí
> Pero ¿qué ***implicaciones*** tiene usar float32 en lugar de usar float64?

In [81]:
a = np.array([0.123456789121212121212,2,3], dtype=np.float16)
print("16bit: ", a[0])

a = np.array([0.123456789121212121212,2,3], dtype=np.float32)
print("32bit: ", a[0])

b = np.array([0.123456789121212121212,2,3], dtype=np.float64)
print("64bit: ", b[0])

16bit:  0.1235
32bit:  0.12345679
64bit:  0.12345678912121212


Si bien los computadores de hoy en día tienen memorias que van desde los 4GB a 128GB o más, también los conjuntos de datos que utilizamos en la vida real pueden tener pesos similares. Entonces evaluar los tipos de datos a usar puede ser una herramienta importante a futuro.

In [82]:
x = 0.1
type(x)

float

----------------------------

## Indexado y acceso

In [83]:
rango = range(1,11)
Np_diez_numeros = np.array(rango)
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
Np_diez_numeros[5]

6

> ***IMPORTANTE:*** En python los indices comienzan en cero.

In [85]:
Np_diez_numeros[-1]

10

In [86]:
Np_diez_numeros[-2]

9



- `Np_diez_numeros[:6]`: Selecciona los primeros 6 elementos del array.
- `Np_diez_numeros[5:]`: Selecciona todos los elementos desde el índice 5 hasta el final del array .
- `Np_diez_numeros[::2]`: Selecciona todos los elementos del array  en incrementos de 2, es decir, selecciona los elementos en las posiciones 0, 2, 4, 6, etc.
- `Np_diez_numeros[1::2]`: Selecciona todos los elementos del array  en incrementos de 2, comenzando desde el índice 1, es decir, selecciona los elementos en las posiciones 1, 3, 5, 7, etc.
- `Np_diez_numerosa[::-1]`: Selecciona todos los elementos del array  en orden inverso.
- `Np_diez_numeros[-5:]`: Selecciona los últimos 5 elementos del array .
- `Np_diez_numeros[2:8:2]`: Selecciona los elementos del array  en las posiciones 2, 4 y 6, es decir, selecciona los elementos en las posiciones 2, 4 y 6.

En general, la indexación por posición en NumPy utiliza la sintaxis `[inicio:fin:paso]`, donde `inicio` es la posición inicial del corte, `fin` es la posición final del corte (no inclusiva) y `paso` es el número de elementos que se saltan en cada iteración. Si alguno de estos valores se omite, se asume que es el valor por defecto (0 para `inicio`, `len(array)` para `fin` y 1 para `paso`).

In [87]:
Np_diez_numeros[::2]

array([1, 3, 5, 7, 9])

In [88]:
Np_diez_numeros[:6]

array([1, 2, 3, 4, 5, 6])

In [89]:
Np_diez_numeros[2:8:2]

array([3, 5, 7])

In [90]:
Np_2_dim = np.random.randint(10, size=(3, 3))
Np_2_dim

array([[9, 7, 2],
       [5, 3, 6],
       [4, 3, 2]])

In [91]:
Np_2_dim[1, 1]

3

In [92]:
Np_3_dim = np.random.randint(10, size=(3, 3, 4))
Np_3_dim

array([[[4, 9, 3, 4],
        [8, 9, 2, 2],
        [7, 8, 6, 9]],

       [[9, 7, 5, 0],
        [8, 0, 7, 3],
        [2, 2, 5, 0]],

       [[8, 6, 5, 8],
        [4, 3, 6, 9],
        [8, 3, 4, 9]]])

In [93]:
"""
se utilizan tres índices, donde el primer índice especifica la matriz,
el segundo índice especifica la fila y el
tercer índice especifica la columna.
"""

Np_3_dim[1, 0, 1]



7

##### Subarrays

In [94]:
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
Np_diez_numeros[0:3]

array([1, 2, 3])

In [96]:
Np_diez_numeros[-3:]

array([ 8,  9, 10])

In [97]:
Np_diez_numeros[7:]

array([ 8,  9, 10])

In [98]:
Np_diez_numeros[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
Np_diez_numeros[::2]

array([1, 3, 5, 7, 9])

In [100]:
Np_diez_numeros[::-2]

array([10,  8,  6,  4,  2])

Como sacar el 5 y el 7?

In [101]:
Np_diez_numeros[4:7]


array([5, 6, 7])

In [102]:
Np_diez_numeros[4:7:2]


array([5, 7])

In [103]:
Np_2_dim

array([[9, 7, 2],
       [5, 3, 6],
       [4, 3, 2]])

In [104]:
Np_2_dim[2,] # fila

array([4, 3, 2])

In [105]:
Np_2_dim[0:2, 0:]

array([[9, 7, 2],
       [5, 3, 6]])

In [106]:
Np_2_dim[0:3,1] # Columna

array([7, 3, 3])

In [107]:
Np_2_dim[:,1]

array([7, 3, 3])

## OPERACIONES BÁSICAS

#### Reshape

In [108]:
unoSeiscuatro = np.arange(1,65)
unoSeiscuatro

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [109]:
unoSeiscuatro.reshape(8,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [110]:
Ajedrez_64 = np.arange(1,65).reshape(2,32)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

#### Concatenación

In [111]:
"""
El código Array_1 = np.random.randint(1000, size=5) crea un array de NumPy llamado Array_1 con 5 elementos enteros aleatorios generados
por la función randint del módulo random de NumPy.

En particular, randint genera números enteros aleatorios en el rango especificado por los argumentos de la función. En este caso, el rango es de 0 a 999
(1000 no está incluido).

Si quisiera float sería np.random.uniform(low=0, high=1000, size=5)
"""

Array_1 = np.random.randint(1000, size=5)
Array_1

array([517, 714, 114, 329, 219])

In [112]:
Array_2 = np.random.randint(100, size=5)
Array_2

array([51, 63, 73,  3, 44])

In [113]:
Arrays_concatenados = np.concatenate([Array_1, Array_2])
Arrays_concatenados

array([517, 714, 114, 329, 219,  51,  63,  73,   3,  44])

In [114]:
Array_apilados_v = np.vstack([Array_1, Array_2])
Array_apilados_v

array([[517, 714, 114, 329, 219],
       [ 51,  63,  73,   3,  44]])

In [115]:
Array_apilados_h = np.hstack([Array_1, Array_2])
Array_apilados_h

array([517, 714, 114, 329, 219,  51,  63,  73,   3,  44])

#### Splitting

In [116]:
Arrays_concatenados

array([517, 714, 114, 329, 219,  51,  63,  73,   3,  44])

In [117]:
Array_partido = np.split(Arrays_concatenados, [6])
Array_partido

[array([517, 714, 114, 329, 219,  51]), array([63, 73,  3, 44])]

### Agregaciones y Operaciones vectorizadas

In [134]:
Array_aleatorio = np.random.randint(1000, size=1000000)
Array_aleatorio

array([126, 110, 980, ..., 271, 789,  68])

In [119]:
len(Array_aleatorio)

1000000

In [135]:
%%time
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma / len(Array_aleatorio)
promedio

CPU times: user 219 ms, sys: 0 ns, total: 219 ms
Wall time: 222 ms


499.404929

In [136]:
%%time
Array_aleatorio.mean()

CPU times: user 2.44 ms, sys: 28 µs, total: 2.47 ms
Wall time: 2.48 ms


499.404929

In [137]:
print("Suma = ", Array_aleatorio.sum())
print("Media o promedio = ", Array_aleatorio.mean())
print("Mínimo = ", Array_aleatorio.min())
print("Máximo = ", Array_aleatorio.max())
print("Mediana = ", np.median(Array_aleatorio))
print("Desviación estándar = ", np.std(Array_aleatorio))
print("Varianza = ", np.var(Array_aleatorio))

Suma =  499404929
Media o promedio =  499.404929
Mínimo =  0
Máximo =  999
Mediana =  499.0
Desviación estándar =  288.6261253724357
Varianza =  83305.04024750496


In [142]:
Array_aleatorio = np.append(Array_aleatorio, np.NaN)


In [143]:
Array_aleatorio

array([126., 110., 980., ...,  68.,  nan,  nan])

In [144]:
Array_aleatorio.mean()

nan

In [146]:
np.nanmean(Array_aleatorio)
#ignora los valores nan

499.404929

#### Operaciones vectorizadas

In [127]:
print(Array_1)
print(Array_2)

[517 714 114 329 219]
[51 63 73  3 44]


In [128]:
Array_1+Array_2

array([568, 777, 187, 332, 263])

In [129]:
np.add(Array_1, Array_2)

array([568, 777, 187, 332, 263])

In [130]:
Array_1+100

array([617, 814, 214, 429, 319])

In [131]:
# Producto vectorial
np.matmul(Array_1, Array_2)

90294